# Generated by Django 4.2.6 on 2024-03-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderador',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
