# Generated by Django 4.2.6 on 2024-03-20 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_moderador_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.moderador'),
        ),
    ]
