# Generated by Django 4.2.6 on 2024-03-20 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sala_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
