# Generated by Django 4.2.6 on 2024-05-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='color',
            field=models.CharField(default='bg-red-400', max_length=10),
        ),
    ]
