name: Profiling

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.14

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run profiling
        env:
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
        run: |
          python -m cProfile -o profile.prof manage.py test
          python -m pstats profile.prof -q -r